### PR TITLE
No Subtitle #92 - Update with YTS API V2

### PR DESCRIPTION
**Pull request by proced**
Hi,
I had a issue with subtitle in a movie in Yifi pop.
So I looking for a solution and i see that the API of YTS is upgrade in V2.

"NOTICE":"This API is deprecated and will not be in use in a few weeks, please update your applications to use APIv2, see our docs for more info"

I make a update for Yifi Pop including the new  V2 API

i hope to be usefull, it's working fine for me.

### CODE REVIEW

**Comment by korrio** [comment]
I've been waiting for this !!
Thank you :dancers:

**Comment by proced** [comment]
You're welcome.
I fixed two bug with cover and search, now it's working exactly the same that before API update

**Comment by korrio** [comment]
yifyResponse.MovieTitleClean 
this return undefined (I checked from the subtitles folder)

**Comment by proced** [comment]
Thanks , i forgot to patch the subtitle directory.

I pull a patch which solve this bug

**Pull request merged**
